services:
  database:
    container_name: pg-database
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: weather-forecast
    ports:
      - "5433:5432"