name: CI/CD weatherForecast with Kubernetes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment (dev, test, prod)'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/weatherForecast
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: ./gradlew test

      - name: Build & push Docker image with Jib
        run: |
          ./gradlew jib \
            -Djib.to.image=$IMAGE_NAME:${{ github.sha }} \
            -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} \
            -Djib.to.auth.password=${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Deploy via Helm
        run: |
          helm upgrade --install weatherForecast ./helm/weatherForecast \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ github.sha }} \
            --set env=${{ env.ENVIRONMENT }} \
            --namespace ${{ env.ENVIRONMENT }} \
            --create-namespace
